spring:
  server:
    port: 8080
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS DB;
      username: sa
      password: sa
    jpa:
      show-sql: true
      generate-ddl: 'true'
      hibernate:
        ddl-auto: 'create-drop'
    h2:
      console.enabled: true
